### ISSUE TITLE
Create Exam page 

### ISSUE THREAD

**Issue by ghost** [ChemiAtlow/YahalomTests#18]
# Exam page 👨🏽‍🏫

## Spec

- The page should get a `testId` route parameter, and should ensure the requested test exists.
- Show the user a form with student info:
   - Email - unique key.
   - First name.
   - Last name.
   - Phone.
- After user fills the form, save/add the student to the DB, and create exam instance in DB and then send it to client.
- The exam instance should have all tests questions, in a random order.
- The client should show the test intro, once the exam instance was returned, and a "start test" button.
- Once test starts, show one question at a time, and show `previous`/`next` buttons.
- Every time student moves between pages, we will save his answer in the DB.
- In last page, show a "End test" button, which will open a prompt to get users approval for test submitting.
- After test has been completed, calculate the grade and:
    - Show the `pass`/`fail` message of the test.
    - Send the `pass`/`fail` email of the test.
    - If student passed the test, show a link to get the certificate.
    - Show the grade the student got, the amount of questions answered correctly, and the total question count.
    - If test is set to allow reviewing, allow checking the test.

### Common

- [x] Add phone to the **Student** model.
- [x] Add `completed` flag to **Exam**, to ensure it is read-only after submitting.
- [x] Add a student DTO to enable validations

### Server

- [x] Create a student repository. (since it has no Id but an email)
- [x] Export a exam repository.
- [x] Add a Student Service.
    - [x] Add/Update student info.
- [x] Add an Exam Service.
    - [x] Build exam instance.
    - [x] Save changes.
    - [x] Lock test. (mark as completed)
    - [x] Get all exams of specific `testId`.
- [x] Add an Exam controller.
    - [x] Ensure a test with given Id exists. (using test service)
    - [x] Build new exam instance - for requested `testId` and `student` info.
    - [x] Save question answer changes.
    - [x] Submit test and return relevant data (message, certificate link, and original questions so we can show how many/which were answered correctly or not).

### React

- [x] Create an exam "landing page" that will show loading message.
- [x] Check with API the requested `testId` is valid, and user can sign up to test.
- [x] After successful sign-up for test, show the test intro page:
    - [x] Show the test name and intro.
    - [x] Show "start exam" button.
- [x] After clicking to start the exam, show pagination of questions, and on each page show current question.
- [x] Last questions page should have a "submit exam" button that sends a lock request.
- [x] After exam was locked, and test results return from server - present `pass`/`fail` message of the exam.
- [x] Show the grade the student got, the amount of questions answered correctly, and the total question count.
- [x] If user passed exam, show link for certificate.
- [x] If exam review is set to true, enable reviewing the exam.

**Comment by ReemCohen** [comment]
Congratulations!
