### ISSUE TITLE
Question form bug

### ISSUE THREAD

**Issue by ghost** [ChemiAtlow/YahalomTests#66]
When changing from **multi choice** to **single choice** all answers stay marked, which could cause multiple "single answers" 😟

**Comment by ChemiAtlow** [comment]
@ReemCohen  We have to discuss how we want to manage this...
Either we keep only 1 marked as correct, or we drop them all.
Perhaps we can show a warning modal, and let user know that by changing he will loose the marked answers

**Comment by ghost** [comment]
@ReemCohen I addressed this issue in #72, but I am unhappy with the solution, which is pretty bad...
